name: Go package

on:
  push:
  schedule:
    - cron: "0 4 * * *" # run once a day at 4 AM

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - name: Build
        run: make build

      - name: Code check
        run: make code-check

      - name: Vulnerabilities
        run: make check-security